// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// random_orthogonal
arma::mat random_orthogonal(int p, int q);
RcppExport SEXP _bifactor_random_orthogonal(SEXP pSEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    rcpp_result_gen = Rcpp::wrap(random_orthogonal(p, q));
    return rcpp_result_gen;
END_RCPP
}
// random_poblq
arma::mat random_poblq(int p, int q, std::vector<arma::uvec> indexes);
RcppExport SEXP _bifactor_random_poblq(SEXP pSEXP, SEXP qSEXP, SEXP indexesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    Rcpp::traits::input_parameter< std::vector<arma::uvec> >::type indexes(indexesSEXP);
    rcpp_result_gen = Rcpp::wrap(random_poblq(p, q, indexes));
    return rcpp_result_gen;
END_RCPP
}
// multiple_rotations
Rcpp::List multiple_rotations(arma::mat loadings, std::string rotation, arma::mat Target, arma::mat Weight, arma::mat Phi_Target, arma::mat Phi_Weight, std::vector<arma::uvec> indexes, double gamma, double epsilon, double k, double w, int random_starts, int cores, double eps, int max_iter);
RcppExport SEXP _bifactor_multiple_rotations(SEXP loadingsSEXP, SEXP rotationSEXP, SEXP TargetSEXP, SEXP WeightSEXP, SEXP Phi_TargetSEXP, SEXP Phi_WeightSEXP, SEXP indexesSEXP, SEXP gammaSEXP, SEXP epsilonSEXP, SEXP kSEXP, SEXP wSEXP, SEXP random_startsSEXP, SEXP coresSEXP, SEXP epsSEXP, SEXP max_iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type loadings(loadingsSEXP);
    Rcpp::traits::input_parameter< std::string >::type rotation(rotationSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Target(TargetSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Weight(WeightSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Phi_Target(Phi_TargetSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Phi_Weight(Phi_WeightSEXP);
    Rcpp::traits::input_parameter< std::vector<arma::uvec> >::type indexes(indexesSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type w(wSEXP);
    Rcpp::traits::input_parameter< int >::type random_starts(random_startsSEXP);
    Rcpp::traits::input_parameter< int >::type cores(coresSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    rcpp_result_gen = Rcpp::wrap(multiple_rotations(loadings, rotation, Target, Weight, Phi_Target, Phi_Weight, indexes, gamma, epsilon, k, w, random_starts, cores, eps, max_iter));
    return rcpp_result_gen;
END_RCPP
}
// efast
Rcpp::List efast(arma::mat R, int n_factors, std::string method, std::string rotation, Rcpp::Nullable<Rcpp::NumericVector> init, Rcpp::Nullable<Rcpp::NumericMatrix> Target, Rcpp::Nullable<Rcpp::NumericMatrix> Weight, Rcpp::Nullable<Rcpp::NumericMatrix> PhiTarget, Rcpp::Nullable<Rcpp::NumericMatrix> PhiWeight, Rcpp::Nullable<Rcpp::List> oblique_indexes, bool normalize, double gamma, double epsilon, double k, double w, int random_starts, int cores, int efa_max_iter, double efa_factr, int m, int rot_max_iter, double rot_eps);
RcppExport SEXP _bifactor_efast(SEXP RSEXP, SEXP n_factorsSEXP, SEXP methodSEXP, SEXP rotationSEXP, SEXP initSEXP, SEXP TargetSEXP, SEXP WeightSEXP, SEXP PhiTargetSEXP, SEXP PhiWeightSEXP, SEXP oblique_indexesSEXP, SEXP normalizeSEXP, SEXP gammaSEXP, SEXP epsilonSEXP, SEXP kSEXP, SEXP wSEXP, SEXP random_startsSEXP, SEXP coresSEXP, SEXP efa_max_iterSEXP, SEXP efa_factrSEXP, SEXP mSEXP, SEXP rot_max_iterSEXP, SEXP rot_epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type R(RSEXP);
    Rcpp::traits::input_parameter< int >::type n_factors(n_factorsSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    Rcpp::traits::input_parameter< std::string >::type rotation(rotationSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type init(initSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericMatrix> >::type Target(TargetSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericMatrix> >::type Weight(WeightSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericMatrix> >::type PhiTarget(PhiTargetSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericMatrix> >::type PhiWeight(PhiWeightSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type oblique_indexes(oblique_indexesSEXP);
    Rcpp::traits::input_parameter< bool >::type normalize(normalizeSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type w(wSEXP);
    Rcpp::traits::input_parameter< int >::type random_starts(random_startsSEXP);
    Rcpp::traits::input_parameter< int >::type cores(coresSEXP);
    Rcpp::traits::input_parameter< int >::type efa_max_iter(efa_max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type efa_factr(efa_factrSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< int >::type rot_max_iter(rot_max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type rot_eps(rot_epsSEXP);
    rcpp_result_gen = Rcpp::wrap(efast(R, n_factors, method, rotation, init, Target, Weight, PhiTarget, PhiWeight, oblique_indexes, normalize, gamma, epsilon, k, w, random_starts, cores, efa_max_iter, efa_factr, m, rot_max_iter, rot_eps));
    return rcpp_result_gen;
END_RCPP
}
// get_target
arma::mat get_target(arma::mat L, arma::mat Phi);
RcppExport SEXP _bifactor_get_target(SEXP LSEXP, SEXP PhiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type L(LSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Phi(PhiSEXP);
    rcpp_result_gen = Rcpp::wrap(get_target(L, Phi));
    return rcpp_result_gen;
END_RCPP
}
// get_target_with_cutoff
arma::mat get_target_with_cutoff(arma::mat L, double cutoff);
RcppExport SEXP _bifactor_get_target_with_cutoff(SEXP LSEXP, SEXP cutoffSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type L(LSEXP);
    Rcpp::traits::input_parameter< double >::type cutoff(cutoffSEXP);
    rcpp_result_gen = Rcpp::wrap(get_target_with_cutoff(L, cutoff));
    return rcpp_result_gen;
END_RCPP
}
// bifactor
Rcpp::List bifactor(arma::mat R, int n_generals, int n_specifics, std::string method, std::string rotation, Rcpp::Nullable<Rcpp::NumericVector> init, bool normalize, double gamma, double epsilon, double k, double w, std::string bifactor_method, int SLiD_max_iter, double cutoff, Rcpp::Nullable<Rcpp::NumericMatrix> LTarget, Rcpp::Nullable<Rcpp::NumericMatrix> PhiTarget, Rcpp::Nullable<Rcpp::NumericMatrix> PhiWeight, Rcpp::Nullable<Rcpp::List> oblique_indexes, int random_starts, int cores, int efa_max_iter, double efa_factr, int m, int rot_max_iter, double rot_eps, bool verbose);
RcppExport SEXP _bifactor_bifactor(SEXP RSEXP, SEXP n_generalsSEXP, SEXP n_specificsSEXP, SEXP methodSEXP, SEXP rotationSEXP, SEXP initSEXP, SEXP normalizeSEXP, SEXP gammaSEXP, SEXP epsilonSEXP, SEXP kSEXP, SEXP wSEXP, SEXP bifactor_methodSEXP, SEXP SLiD_max_iterSEXP, SEXP cutoffSEXP, SEXP LTargetSEXP, SEXP PhiTargetSEXP, SEXP PhiWeightSEXP, SEXP oblique_indexesSEXP, SEXP random_startsSEXP, SEXP coresSEXP, SEXP efa_max_iterSEXP, SEXP efa_factrSEXP, SEXP mSEXP, SEXP rot_max_iterSEXP, SEXP rot_epsSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type R(RSEXP);
    Rcpp::traits::input_parameter< int >::type n_generals(n_generalsSEXP);
    Rcpp::traits::input_parameter< int >::type n_specifics(n_specificsSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    Rcpp::traits::input_parameter< std::string >::type rotation(rotationSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type init(initSEXP);
    Rcpp::traits::input_parameter< bool >::type normalize(normalizeSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type w(wSEXP);
    Rcpp::traits::input_parameter< std::string >::type bifactor_method(bifactor_methodSEXP);
    Rcpp::traits::input_parameter< int >::type SLiD_max_iter(SLiD_max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type cutoff(cutoffSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericMatrix> >::type LTarget(LTargetSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericMatrix> >::type PhiTarget(PhiTargetSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericMatrix> >::type PhiWeight(PhiWeightSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type oblique_indexes(oblique_indexesSEXP);
    Rcpp::traits::input_parameter< int >::type random_starts(random_startsSEXP);
    Rcpp::traits::input_parameter< int >::type cores(coresSEXP);
    Rcpp::traits::input_parameter< int >::type efa_max_iter(efa_max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type efa_factr(efa_factrSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< int >::type rot_max_iter(rot_max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type rot_eps(rot_epsSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(bifactor(R, n_generals, n_specifics, method, rotation, init, normalize, gamma, epsilon, k, w, bifactor_method, SLiD_max_iter, cutoff, LTarget, PhiTarget, PhiWeight, oblique_indexes, random_starts, cores, efa_max_iter, efa_factr, m, rot_max_iter, rot_eps, verbose));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_bifactor_random_orthogonal", (DL_FUNC) &_bifactor_random_orthogonal, 2},
    {"_bifactor_random_poblq", (DL_FUNC) &_bifactor_random_poblq, 3},
    {"_bifactor_multiple_rotations", (DL_FUNC) &_bifactor_multiple_rotations, 15},
    {"_bifactor_efast", (DL_FUNC) &_bifactor_efast, 22},
    {"_bifactor_get_target", (DL_FUNC) &_bifactor_get_target, 2},
    {"_bifactor_get_target_with_cutoff", (DL_FUNC) &_bifactor_get_target_with_cutoff, 2},
    {"_bifactor_bifactor", (DL_FUNC) &_bifactor_bifactor, 26},
    {NULL, NULL, 0}
};

RcppExport void R_init_bifactor(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
