# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

smoothing <- function(X, min_eigval = 0.001) {
    .Call(`_bifactor_smoothing`, X, min_eigval)
}

random_orth <- function(p, q) {
    .Call(`_bifactor_random_orth`, p, q)
}

random_oblq <- function(p, q) {
    .Call(`_bifactor_random_oblq`, p, q)
}

random_poblq <- function(p, q, oblq_factors) {
    .Call(`_bifactor_random_poblq`, p, q, oblq_factors)
}

retr_orth <- function(X) {
    .Call(`_bifactor_retr_orth`, X)
}

retr_oblq <- function(X) {
    .Call(`_bifactor_retr_oblq`, X)
}

retr_poblq <- function(X, oblq_factors) {
    .Call(`_bifactor_retr_poblq`, X, oblq_factors)
}

sl <- function(R, n_generals, n_groups, nobs = NULL, first_efa = NULL, second_efa = NULL) {
    .Call(`_bifactor_sl`, R, n_generals, n_groups, nobs, first_efa, second_efa)
}

rotate <- function(loadings, rotation = as.character( c("oblimin")), projection = "oblq", gamma = 0L, epsilon = as.numeric( c(0.01)), k = 0L, w = 1, Target = NULL, Weight = NULL, PhiTarget = NULL, PhiWeight = NULL, blocks = NULL, block_weights = NULL, oblq_factors = NULL, normalization = "none", rot_control = NULL, random_starts = 1L, cores = 1L) {
    .Call(`_bifactor_rotate`, loadings, rotation, projection, gamma, epsilon, k, w, Target, Weight, PhiTarget, PhiWeight, blocks, block_weights, oblq_factors, normalization, rot_control, random_starts, cores)
}

efast <- function(X, nfactors, cor = "pearson", method = "minres", rotation = as.character( c("oblimin")), projection = "oblq", nobs = NULL, Target = NULL, Weight = NULL, PhiTarget = NULL, PhiWeight = NULL, blocks = NULL, block_weights = NULL, oblq_factors = NULL, gamma = 0L, epsilon = as.numeric( c(0.01)), k = 0L, w = 1, random_starts = 1L, cores = 1L, init = NULL, efa_control = NULL, rot_control = NULL) {
    .Call(`_bifactor_efast`, X, nfactors, cor, method, rotation, projection, nobs, Target, Weight, PhiTarget, PhiWeight, blocks, block_weights, oblq_factors, gamma, epsilon, k, w, random_starts, cores, init, efa_control, rot_control)
}

get_target <- function(loadings, Phi, cutoff = 0) {
    .Call(`_bifactor_get_target`, loadings, Phi, cutoff)
}

bifactor <- function(R, n_generals, n_groups, bifactor_method = "GSLiD", method = "minres", projection = "oblq", nobs = NULL, PhiTarget = NULL, PhiWeight = NULL, blocks = NULL, block_weights = NULL, oblq_factors = NULL, init_Target = NULL, maxit = 20L, cutoff = 0, normalization = "none", w = 1, random_starts = 1L, cores = 1L, init = NULL, efa_control = NULL, rot_control = NULL, first_efa = NULL, second_efa = NULL, verbose = TRUE) {
    .Call(`_bifactor_bifactor`, R, n_generals, n_groups, bifactor_method, method, projection, nobs, PhiTarget, PhiWeight, blocks, block_weights, oblq_factors, init_Target, maxit, cutoff, normalization, w, random_starts, cores, init, efa_control, rot_control, first_efa, second_efa, verbose)
}

asymp_cov <- function(R, X = NULL, eta = 1, type = "normal") {
    .Call(`_bifactor_asymp_cov`, R, X, eta, type)
}

se <- function(fit = NULL, nobs = NULL, X = NULL, type = "normal", eta = 1) {
    .Call(`_bifactor_se`, fit, nobs, X, type, eta)
}

parallel <- function(X, n_boot = 100L, type = "pearson", quant = NULL, mean = FALSE, replace = FALSE, PA = NULL, hierarchical = FALSE, efa = NULL, cores = 1L) {
    .Call(`_bifactor_parallel`, X, n_boot, type, quant, mean, replace, PA, hierarchical, efa, cores)
}

cv_eigen <- function(X, N = 100L, hierarchical = FALSE, efa = NULL, cores = 1L) {
    .Call(`_bifactor_cv_eigen`, X, N, hierarchical, efa, cores)
}

check_deriv <- function(L, Phi, dL, dP, rotation = as.character( c("oblimin")), projection = "oblq", Target = NULL, Weight = NULL, PhiTarget = NULL, PhiWeight = NULL, blocks = NULL, block_weights = NULL, oblq_factors = NULL, gamma = 0L, epsilon = as.numeric( c(0.01)), k = 0L, w = 1) {
    .Call(`_bifactor_check_deriv`, L, Phi, dL, dP, rotation, projection, Target, Weight, PhiTarget, PhiWeight, blocks, block_weights, oblq_factors, gamma, epsilon, k, w)
}

polyfast <- function(X, acov = "none", PD = FALSE, nboot = 1000L, fit = FALSE, cores = 1L) {
    .Call(`_bifactor_polyfast`, X, acov, PD, nboot, fit, cores)
}

poly2 <- function(X, cores) {
    .Call(`_bifactor_poly2`, X, cores)
}

fpoly <- function(X, S) {
    .Call(`_bifactor_fpoly`, X, S)
}

old_poly <- function(X, cores) {
    .Call(`_bifactor_old_poly`, X, cores)
}

joint_frequency_table <- function(X, n, max_X, Y, max_Y) {
    .Call(`_bifactor_joint_frequency_table`, X, n, max_X, Y, max_Y)
}

COV2 <- function(rho, tau1, tau2, mvphi1, mvphi2) {
    .Call(`_bifactor_COV2`, rho, tau1, tau2, mvphi1, mvphi2)
}

std_2_matrix <- function(tabs, n) {
    .Call(`_bifactor_std_2_matrix`, tabs, n)
}

